### ISSUE TITLE
Add Camera3d.projectionMatrix

### ISSUE THREAD

**Issue by MartinSStewart** [opensolid/webgl#7]
Unless I've misunderstood something, there doesn't seem to be any way to get the projection matrix of a camera. This means while I can use `Camera3d` to get the model and view matrix, I have to resort to `Math.Matrix4.makePerspective` from `elm-explorations/linear-algebra` for the last part.

I think while adding this, it would also make sense to have `Camera3d.viewProjectionMatrix` and `Camera3d.modelViewProjectionMatrix`.

**Comment by ianmackenzie** [comment]
Yeah, I probably should re-add those; the reason they're not in right now is that I don't actually use a projection matrix in `elm-3d-scene`, I've switched to using a `vec4` of "projection parameters". See [here](https://github.com/ianmackenzie/elm-3d-scene/blob/dce6bd480e4615c4c795891136609e7234aec35d/src/Scene3d/Shaders.elm#L58) for the GLSL code that actually uses those properties; the reason I decided to go that route was because I realized that orthographic and perspective projection matrices actually calculate Z values in very different ways, and I didn't want there to be cases where (for example) you'd get Z-fighting with orthographic projection but not perspective projection.

**Comment by ianmackenzie** [comment]
Projection matrices are back now! (The "projection parameters" thing didn't actually work due to issues with things like perspective-correct interpolation, so I had to revert back to traditional projection matrices.)
